### ISSUE TITLE
Meta: Regressions from the vertex declaration refactoring

### ISSUE THREAD

**Issue by CookiePLMonster** [Cxbx-Reloaded/Cxbx-Reloaded#2114]
## Quick summary
We've had enough reported regressions caused by `CI-213dd2f` (vertex declaration refactoring) to warrant a tracker for those.

## Details
* [ ] [Tony Hawk's Pro Skater 2X](https://cxbx-reloaded.co.uk/compatibility/title/2165) - broken geometry
* [ ] [The Warriors](https://cxbx-reloaded.co.uk/compatibility/title/2092) - R* intro logo is now pink, not yellow - blue-to-alpha changes possibly got partially reverted?
* [ ] [Crash Nitro Kart](https://cxbx-reloaded.co.uk/compatibility/title/360) - broken menus

### System Configuration:
N/A

### Additional Information (if any):
N/A

**Comment by lesebio** [comment]
Sonic Heroes - flickering characters textures
